name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Curl Request
        run: curl https://erp-rag-assistant-1.onrender.com/health